### ISSUE TITLE
No communication?

### ISSUE THREAD

**Issue by danielplangis** [sparkfun/MiniGen#1]
Has anyone used this board and library successfully?

I have my MiniGen hooked up to an Arduino Uno at the moment (using 3.3 V, with pins connected to SPI pins as appropriate).

When I upload the code, the MiniGen outputs a clean 1.09 Vpp sine wave, running at 62.5 kHz.  However, the Library Test code (or any of my attempts to modify it) don't seem to be updating any of the registers on the MiniGen itself to change the frequency or  wave type.  It seems to be stuck where it is. 

I have used SPI communication with the DS3234 "Dead-on RTC" successfully before for writing registers and alarms.  Doesn't seem to be working here though.  Any suggestions on where to start?

**Comment by ToniCorinne** [comment]
Apologies on the long delay in answering this. For anyone who also might be having issues with this, please keep in mind this spec point:

> By default, the MiniGen ships configured with a 3.3V regulator enabled and should only be used with 3.3V signals (or 3.3V Pro Minis if you are using this as a shield) unless the jumper on the back is soldered over to bypass the regulator for 5V use.

Double check that you are using signals at the appropriate voltage when interfacing with the board to ensure proper functionality. 

Closing this issue out, but if you do still have additional questions, please let us know.
